spring:
  application:
    name: "authentication"

  config:
    import: "optional:configserver:http://192.168.1.100:9092/"

  datasource:
    url: jdbc:mysql://192.168.1.100:3306/authdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  app:
    jwtSecret: "udayshastrakarnfdjnfjdnjvndjnvjnjnjndjvfcndkjnvjkndjncndnndjvnjkndjknvjknjfnvkjndfnvkjdnjkdnjknkjnvnjdfknvdnvfvfdv"
    jwtExpirationMs: 3000000

info:
  app:
    name: "authentication"
    description: "Bank authentication Server Application"
    version: "1.0"

feign:
  client:
    config:
      card-service:
        url: ${my-client.url}
      account-service:
        url: ${account-service.url}
      customer-service:
        url: ${customer-service.url}
      email-service:
        url: ${email-service.url}

# Add URLs for service feign clients
card-service:
  url: http://192.168.1.100:9096

account-service:
  url: http://192.168.1.100:9095

customer-service:
  url: http://192.168.1.100:9094

email-service:
  url: http://192.168.1.100:9097

server:
  port: 9093

logging:
  level:
    feign:
      client:
        config:
          default: TRACE
          email-service: TRACE
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    com.example.authentication: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.1.100:8761/eureka
