spring:
  application:
    name: "customer"

  datasource:
    url: jdbc:mysql://192.168.1.100:3306/customer
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml


info:
  app:
    name: "customer"
    description: "Application for online banking accounts."
    version: "1.0"

server:
  port: 9094

