spring:
  application:
    name: "gateway"
  
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
info:
  app:
    name: "gatewayserver"
    description: "Bank Gateway Server Application"
    version: "1.0"

logging:
  level:
    com:
      bank:
        gatewayserver: DEBUG

server:
  port: 9091

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.1.100:8761/eureka




eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.1.100:8761/eureka
